blank_issues_enabled: false
contact_links:
  - name: Documentation issue
    url: https://github.com/laravel-backpack/docs
    about: Please open an issue or pull request in our docs repository.
  - name: How Do I X?
    url: https://github.com/Laravel-Backpack/community-forum/discussions
    about: Please use Discussions in our community forum. We've been blessed with a great community, that is happy to help.
  - name: Idea or Feature Request
    url: https://github.com/Laravel-Backpack/community-forum/discussions/new
    about: If you have an idea, question or problem and you don't know where it fits, use our Community Forum. This is where we hang out and talk about all kinds of stuff.
